spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    url: jdbc:h2:mem:teamdb
    password:
    dbname: teamdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate